name: build
on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build app
        uses: gradle/gradle-command-action@v2
        with:
          arguments: genSources build

      - name: list files
        run: ls -ltR | grep .jar
